[GOBBLIN-1497] Reduce the number of calls on FlowSpec initialization where possible,…
apache/gobblin pull request #3340
Opened 2021-07-26 23:38 UTC by Will-Lo

… and configToProperties/vice versa

Dear Gobblin maintainers,

Please accept this PR. I understand that it will not be reviewed until I have checked off all the steps below!

### JIRA
- [ ] My PR addresses the following [Gobblin JIRA](https://issues.apache.org/jira/browse/GOBBLIN/) issues and references them in the PR title. For example, "[GOBBLIN-XXX] My Gobblin PR"
    - https://issues.apache.org/jira/browse/GOBBLIN-1497

### Description
- [ ] Here are some details about my PR, including screenshots (if applicable):

FlowSpecs contain both configs and property fields that duplicate the same key/value information, however there are slight differences with properties being mutable, configs being type-safe, and legacy code being compatible with properties but not configs.

As such, FlowSpec creation and configToProperties are memory expensive operations at scale, and we should aim to minimize them as much as possible.

### Tests
- [ ] My PR adds the following unit tests __OR__ does not need testing for this extremely good reason:

### Commits
- [ ] My commits all reference JIRA issues in their subject lines, and I have squashed multiple commits if they address the same issue. In addition, my commits follow the guidelines from "[How to write a good git commit message](http://chris.beams.io/posts/git-commit/)":
    1. Subject is separated from body by a blank line
    2. Subject is limited to 50 characters
    3. Subject does not end with a period
    4. Subject uses the imperative mood ("add", not "adding")
    5. Body wraps at 72 characters
    6. Body explains "what" and "why", not "how"

2021-07-27 20:17 UTC, Will-Lo commented
@arjun4084346 @jack-moseley @umustafi could you take a look?

2021-07-27 21:24 UTC, arjun4084346 commented on gobblin-service/src/main/java/org/apache/gobblin/service/modules/restli/FlowConfigUtils.java
> +    Properties properties = PropertiesUtils.stringMapToProperties(flowConfig.getProperties());
`Properties properties = new Properties().putAll(flowConfig.getProperties());` works

2021-07-27 21:24 UTC, arjun4084346 commented on gobblin-utility/src/main/java/org/apache/gobblin/util/PropertiesUtils.java
> +    Properties properties = new Properties();
equivalent to putAll()

2021-07-27 21:26 UTC, arjun4084346 commented
minor comments to simply things. LGTM otherwise. good changes. maybe we should get rid of configAsProperties entirely. but that may need more changes.

2021-07-27 23:49 UTC, Will-Lo commented
@arjun4084346 yea we should look into configAsProperties especially at the rate that GaaS is growing at. Would require some refactoring around some legacy classes and probably more conversions from propertiesToConfig. However since those would be short-lived compared to FlowSpecs it would still be an overall memory improvement

2021-07-27 23:53 UTC, umustafi approved these changes
These replacements look good!

2021-07-28 19:54 UTC, sv2000 commented on gobblin-service/src/main/java/org/apache/gobblin/service/modules/scheduler/GobblinServiceJobScheduler.java
> +            .getProperty(ConfigurationKeys.FLOW_RUN_IMMEDIATELY, "false").equals("true")) {
Use PropertiesUtils.getPropAsBoolean() here and check for the boolean instead of the string value.

2021-07-28 19:54 UTC, sv2000 requested changes
A minor comment.

2021-07-28 22:31 UTC, sv2000 approved these changes
+1.

2021-07-28 22:32 UTC, merged