[GOBBLIN-1630] Remove flow level metrics for adhoc flows
apache/gobblin pull request #3491
Opened 2022-04-12 01:14 UTC by Will-Lo

Dear Gobblin maintainers,

Please accept this PR. I understand that it will not be reviewed until I have checked off all the steps below!

### JIRA
- [x] My PR addresses the following [Gobblin JIRA](https://issues.apache.org/jira/browse/GOBBLIN/) issues and references them in the PR title. For example, "[GOBBLIN-XXX] My Gobblin PR"
    - https://issues.apache.org/jira/browse/GOBBLIN-1630

### Description
- [x] Here are some details about my PR, including screenshots (if applicable):
Gobblin-as-a-Service emits flow level events for users to keep track of their flow compilation status, job status, number of workunits etc. However, users rarely if ever track adhoc-flows, where they are generally used in a fire-and-forget manner. Furthermore, keeping track of metrics continuously adds strains to the metric libraries which leads to wasted resources.

We should only be emitting flow level events for flows that are scheduled and saved.

This PR adds a flag for adhoc flows such that downstream executions can also differentiate scheduled and adhoc flows, so that downstream workloads can also prevent the emission of metrics for these flows that are not tracked.

### Tests
- [x] My PR adds the following unit tests __OR__ does not need testing for this extremely good reason:

### Commits
- [x] My commits all reference JIRA issues in their subject lines, and I have squashed multiple commits if they address the same issue. In addition, my commits follow the guidelines from "[How to write a good git commit message](http://chris.beams.io/posts/git-commit/)":
    1. Subject is separated from body by a blank line
    2. Subject is limited to 50 characters
    3. Subject does not end with a period
    4. Subject uses the imperative mood ("add", not "adding")
    5. Body wraps at 72 characters
    6. Body explains "what" and "why", not "how"

2022-04-14 09:45 UTC, phet reviewed
nice tests, BTW!

2022-04-14 09:45 UTC, phet commented on gobblin-api/src/main/java/org/apache/gobblin/configuration/ConfigurationKeys.java
> +  public static final String GOBBLIN_FLOW_ISADHOC = "gobblin.flow.isAdhoc";
should we debug a separate namespace for these, which are meant to be internal-only, not to be supplied by a user?  e.g. `gobblin.internal.flow.isAdhoc`

2022-04-14 09:45 UTC, phet commented on gobblin-service/src/main/java/org/apache/gobblin/service/modules/orchestration/DagManagerUtils.java
> +    return ConfigUtils.getBoolean(dag.getStartNodes().get(0).getValue().getJobSpec().getConfig(), ConfigurationKeys.GOBBLIN_FLOW_ISADHOC,false);
if `DagMgrUtils` doesn't yet have an abstraction for getting a DAG's job config, we might consider one:
```
.getStartNodes().get(0).getValue().getJobSpec().getConfig()
```

2022-04-14 09:45 UTC, phet commented on gobblin-service/src/main/java/org/apache/gobblin/service/modules/orchestration/Orchestrator.java
> +          flowGauges.get(spec.getUri().toString()).setState(CompiledState.SKIPPED);
consider abstracting, e.g. to:
```
conditionallyUpdateFlowGaugeSpecState(flowGauges, spec, state)
```
OR
```
updateSpecStateIfFlowGauge(spec, state, flowGauges)
```

2022-04-15 04:37 UTC, phet approved these changes

2022-04-15 20:01 UTC, ZihanLi58 requested changes

2022-04-18 23:37 UTC, ZihanLi58 commented on gobblin-service/src/main/java/org/apache/gobblin/service/modules/orchestration/Orchestrator.java
> +  /**
Synced offline and seems the types of guage  are different and make it difficult to merge two methods, no need to address in this PR

2022-04-18 23:37 UTC, ZihanLi58 approved these changes
+1

2022-04-18 23:37 UTC, merged