[GOBBLIN-1668] Add audit counts for iceberg registration
apache/gobblin pull request #3527
Opened 2022-07-11 22:29 UTC by jack-moseley

Dear Gobblin maintainers,

Please accept this PR. I understand that it will not be reviewed until I have checked off all the steps below!

### JIRA
- [x] My PR addresses the following [Gobblin JIRA](https://issues.apache.org/jira/browse/GOBBLIN/) issues and references them in the PR title. For example, "[GOBBLIN-XXX] My Gobblin PR"
    - https://issues.apache.org/jira/browse/GOBBLIN-1668

### Description
- [x] Here are some details about my PR, including screenshots (if applicable):
Pass audit count maps from streaming through a new field in GMCE, then publish those counts to a new tier after iceberg registration is done.

- Add a new field in GMCE to contain a serialized audit map string
- Populate this in MCE publisher using key `SERIALIZED_AUDIT_MAP_KEY` (will be set internally)
- After iceberg commit, call sendAuditCounts using the map from the GMCE (will be implemented internally)
- Also use a new WhitelistBlacklist for sending these audit counts, because we may want to count only for specific dbs.

### Tests
- [x] My PR adds the following unit tests __OR__ does not need testing for this extremely good reason:
Tested in parallel pipeline

### Commits
- [x] My commits all reference JIRA issues in their subject lines, and I have squashed multiple commits if they address the same issue. In addition, my commits follow the guidelines from "[How to write a good git commit message](http://chris.beams.io/posts/git-commit/)":
    1. Subject is separated from body by a blank line
    2. Subject is limited to 50 characters
    3. Subject does not end with a period
    4. Subject uses the imperative mood ("add", not "adding")
    5. Body wraps at 72 characters
    6. Body explains "what" and "why", not "how"

2022-07-14 00:40 UTC, vikrambohra requested changes

2022-07-14 00:40 UTC, vikrambohra commented on gobblin-iceberg/src/main/java/org/apache/gobblin/iceberg/writer/IcebergMetadataWriter.java
> +  private static final String ICEBERG_REGISTRATION_AUDIT_BLACKLIST = "iceberg.registration.audit.blacklist";
iceberg.registration.audit.counts.blacklist?

2022-07-14 00:40 UTC, vikrambohra commented on gobblin-iceberg/src/main/java/org/apache/gobblin/iceberg/writer/IcebergMetadataWriter.java
> +  public void sendAuditCounts(String topicName, List<String> serializedAuditCountMaps) {
Add javadoc to this method explaining the intention. Also, can we change to Collection<String> instead of List<String>

2022-07-14 00:40 UTC, vikrambohra commented on gobblin-iceberg/src/main/java/org/apache/gobblin/iceberg/writer/IcebergMetadataWriter.java
> +    tableMetadata.serializedAuditCountMaps.add(gmce.getAuditCountMap());
Null check since gmce.getAuditCountMap is nullable.

2022-07-14 00:40 UTC, vikrambohra commented on gobblin-iceberg/src/main/java/org/apache/gobblin/iceberg/GobblinMCEProducer.java
> +    if (serializedAuditMap != null) {
the not null check seems redundant if the auditCountsMap default is nullable.

2022-07-14 18:14 UTC, vikrambohra requested changes

2022-07-14 18:14 UTC, vikrambohra commented on gobblin-iceberg/src/main/java/org/apache/gobblin/iceberg/GobblinMCEProducer.java
> +      Map<String, String> offsetRange, OperationType operationType, SchemaSource schemaSource, String serializedAuditMap) throws IOException {
serializedAuditCountMap?

2022-07-14 18:14 UTC, vikrambohra commented on gobblin-iceberg/src/main/java/org/apache/gobblin/iceberg/GobblinMCEProducer.java
> +
Add javadoc with the new parameter

2022-07-14 18:14 UTC, vikrambohra commented on gobblin-iceberg/src/main/java/org/apache/gobblin/iceberg/GobblinMCEProducer.java
> +      SchemaSource schemaSource, String serializedAuditMap) {
serializedAuditCountMap?

2022-07-14 18:14 UTC, vikrambohra commented on gobblin-iceberg/src/main/java/org/apache/gobblin/iceberg/writer/IcebergMetadataWriter.java
> +          if (auditWhitelistBlacklist.acceptTable(dbName, tableName)) {
There is a chance of optimization here. We should check if a table should be audited when collecting the counts rather than publish time.

2022-07-14 18:14 UTC, vikrambohra commented on gobblin-iceberg/src/main/java/org/apache/gobblin/iceberg/writer/IcebergMetadataWriter.java
> +    tableMetadata.serializedAuditCountMaps.add(gmce.getAuditCountMap());
See my below comment about collecting audit counts only if the table is whitelisted

2022-07-18 19:04 UTC, ZihanLi58 approved these changes
+1

2022-07-18 19:04 UTC, merged