[GOBBLIN-1815] Refactor yarn app launchers to support extending these classes
apache/gobblin pull request #3671
Opened 2023-04-11 16:50 UTC by arjun4084346

Dear Gobblin maintainers,

Please accept this PR. I understand that it will not be reviewed until I have checked off all the steps below!

### JIRA
- [x] My PR addresses the following [Gobblin JIRA](https://issues.apache.org/jira/browse/GOBBLIN/) issues and references them in the PR title. For example, "[GOBBLIN-XXX] My Gobblin PR"
    - https://issues.apache.org/jira/browse/GOBBLIN-1815

### Description
- [x] Here are some details about my PR, including screenshots (if applicable):
did some minor refactoring so that child classes can override a part of the logic

### Tests
- [x] My PR adds the following unit tests __OR__ does not need testing for this extremely good reason:
trivial changes

### Commits
- [x] My commits all reference JIRA issues in their subject lines, and I have squashed multiple commits if they address the same issue. In addition, my commits follow the guidelines from "[How to write a good git commit message](http://chris.beams.io/posts/git-commit/)":
    1. Subject is separated from body by a blank line
    2. Subject is limited to 50 characters
    3. Subject does not end with a period
    4. Subject uses the imperative mood ("add", not "adding")
    5. Body wraps at 72 characters
    6. Body explains "what" and "why", not "how"

2023-04-12 22:41 UTC, jack-moseley requested changes

2023-04-13 00:38 UTC, arjun4084346 commented on gobblin-yarn/src/main/java/org/apache/gobblin/yarn/GobblinYarnAppLauncher.java
> +  protected void createPotentonYarnClients(Config config, Map<String, YarnClient> potentialYarnClients) {
Oh yes, thanks

2023-04-13 00:48 UTC, jack-moseley approved these changes

2023-04-13 16:29 UTC, Will-Lo approved these changes

2023-04-13 16:29 UTC, merged